---
name: MDBF deployment

on:
  push:
    paths:
      - .github/workflows/test_mdbf.yml
      - requirements.txt
      - "files/**"
      - "handlers/**"
      - "molecule/default/**"
      - "tasks/**"
      - "templates/**"
      - "vars/**"
  pull_request:
    paths:
      - .github/workflows/test_mdbf.yml
      - requirements.txt
      - "files/**"
      - "handlers/**"
      - "molecule/default/**"
      - "tasks/**"
      - "templates/**"
      - "vars/**"
  schedule:
    - cron: "10 5 * * 2"

jobs:
  molecule-mdbf-pkg:
    name: MDBF
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        distro:
          - ubuntu-20.04
          - ubuntu-22.04
          - ubuntu-23.04
          - debian-10
          - debian-11
          - debian-12
          - debian-sid
          - fedora-38
          - fedora-39
          # - almalinux-8
          - almalinux-9
          # - rockylinux-8
          - rockylinux-9
        mariadb-version:
          - "10.4"
          - "10.5"
          - "10.6"
          - "10.11"
          - "11.0"
          - "11.1"
          - "11.2"
          - "11.3"
          - "11.4"
          - "11.rc"
          - "11.rolling"
        exclude:
          - distro: ubuntu-22.04
            mariadb-version: 10.4
          - distro: ubuntu-22.04
            mariadb-version: 10.5
          - distro: ubuntu-23.04
            mariadb-version: 10.4
          - distro: ubuntu-23.04
            mariadb-version: 10.5
          - distro: ubuntu-23.04
            mariadb-version: 10.6
          - distro: debian-11
            mariadb-version: 10.4
          - distro: debian-12
            mariadb-version: 10.4
          - distro: debian-12
            mariadb-version: 10.5
          - distro: debian-12
            mariadb-version: 10.6
          - distro: debian-sid
            mariadb-version: 10.4
          - distro: debian-sid
            mariadb-version: 10.5
          - distro: fedora-37
            mariadb-version: 10.4
          - distro: fedora-37
            mariadb-version: 10.5
          - distro: fedora-38
            mariadb-version: 10.4
          - distro: fedora-38
            mariadb-version: 10.5
          - distro: almalinux-9
            mariadb-version: 10.4
          - distro: rockylinux-9
            mariadb-version: 10.4

    steps:
      - uses: actions/checkout@v4
      - name: Setup environment
        uses: ./.github/workflows/composite-action
      - name: Run molecule
        run: |
          source .venv/bin/activate
          molecule test
        env:
          PY_COLORS: "1"
          ANSIBLE_FORCE_COLOR: "1"
          MOLECULE_DISTRO: ${{ matrix.distro }}
          MOLECULE_PLAYBOOK: mdbf.yml
          MARIADB_VERSION: ${{ matrix.mariadb-version }}
