---
name: Default deployment

on:
  push:
    paths:
      - "files/**"
      - "handlers/**"
      - "molecule/default/**"
      - "tasks/**"
      - "templates/**"
      - "vars/**"
      - .github/workflows/composite-action/action.yml
      - .github/workflows/test_default.yml
      - requirements.txt
  pull_request:
    paths:
      - "files/**"
      - "handlers/**"
      - "molecule/default/**"
      - "tasks/**"
      - "templates/**"
      - "vars/**"
      - .github/workflows/composite-action/action.yml
      - .github/workflows/test_default.yml
      - requirements.txt
  schedule:
    - cron: "0 5 * * 2"

jobs:
  molecule-distrib-pkg:
    name: Default deployment
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        distro:
          # - ubuntu-18.04
          - ubuntu-20.04
          - ubuntu-22.04
          - debian-11
          - debian-12
          - debian-sid
          - fedora-40
          - fedora-41
          # - almalinux-8
          - almalinux-9
          # - rockylinux-8
          - rockylinux-9
          - alpine-3.17
          - alpine-3.18
          - alpine-3.19
          - alpine-3.20
          - alpine-3.21
    steps:
      - uses: actions/checkout@v4
      - name: Setup environment
        uses: ./.github/workflows/composite-action
      - name: Run molecule
        run: |
          source .venv/bin/activate
          molecule test
        env:
          PY_COLORS: "1"
          ANSIBLE_FORCE_COLOR: "1"
          MOLECULE_DISTRO: ${{ matrix.distro }}
