---
name: Cluster MDBF

on:
  push:
    paths:
      - .github/workflows/test_cluster_mdbf.yml
      - requirements.txt
      - "files/**"
      - "handlers/**"
      - "molecule/cluster/**"
      - "tasks/**"
      - "templates/**"
      - "vars/**"
  pull_request:
    paths:
      - .github/workflows/test_cluster_mdbf.yml
      - requirements.txt
      - "files/**"
      - "handlers/**"
      - "molecule/cluster/**"
      - "tasks/**"
      - "templates/**"
      - "vars/**"
  schedule:
    - cron: "30 5 * * 2"

jobs:
  molecule-cluster-pkg:
    name: Cluster MDBF
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        distro:
          - ubuntu-20.04
          - ubuntu-22.04
          - debian-12
          - fedora-38
          - almalinux-8
          - almalinux-9
          - rockylinux-8
          - rockylinux-9
        mariadb-version:
          - "10.6"
          - "10.11"
          - "11.0"
          - "11.1"
          - "11.2"
          - "11.rc"
          - "11.rolling"
        exclude:
          - distro: debian-12
            mariadb-version: 10.6
    steps:
      - uses: actions/checkout@v4
      - name: Setup environment
        uses: ./.github/workflows/composite-action
      - name: Run molecule
        run: |
          source .venv/bin/activate
          molecule test -s cluster
        env:
          PY_COLORS: "1"
          ANSIBLE_FORCE_COLOR: "1"
          MOLECULE_DISTRO: ${{ matrix.distro }}
          MOLECULE_PLAYBOOK: mdbf.yml
          MARIADB_VERSION: ${{ matrix.mariadb-version }}
